### ISSUE TITLE
Nuevo catálogo de CCE fracciones arancelarias

### ISSUE THREAD

**Issue by eclipxe13** [phpcfdi/sat-catalogos-populate#1]
A partir de 2020-12-28 el SAT publicó un nuevo catálogo de fracciones arancelarias para el Complemento de Comercio Exterior.

En la siguiente dirección se pueden ver los dos catálogos: http://omawww.sat.gob.mx/tramitesyservicios/Paginas/catalogos_emision_cfdi_complemento_ce.htm

**Catálogo vigente hasta el 27 de diciembre de 2020**
Es el catálogo que actualmente se procesa por esta herramienta y todas las entradas están marcadas como no vigentes.

**Catálogo vigente a partir del 28 de diciembre de 2020**
Este catálogo sigue la misma estructura del catálogo previo y contiene las nuevas fracciones arancelarias a 10 dígitos.
- La dirección de descarga no es constante, ahora es una dirección variable.
- En algún momento la estructura del catálogo podría ser diferente, por lo que sería incompatible con la versión de 8 dígitos.

Esta situación genera los siguientes retos:

1. Se debe crear un nuevo método para poder extraer el nuevo catálogo de dirección variable. Actualmente la librería solo funciona con direcciones contantes.
2. ¿Se va a utilizar la misma tabla de fracciones arancelarias o se usará una nueva?
    * Si es un nuevo catálogo se tratarán como dos conceptos diferentes cuando en realidad se refiere a uno mismo, podría hacer más fácil la importación de datos pero más difícil la exportación.
    * Si es el mismo catálogo, se debe hacer que la importación de datos sea de dos orígenes en lugar de solo uno, además de plantear qué hacer en caso de que la estructura de datos del nuevo catálogo cambie en un futuro.

**Comment by valhallaws** [comment]
Considero que debería ser sobre la misma tabla el movimiento. Con un alter table para modificar el máximo del campo.

Personalmente you hago la consulta de la base de datos directamente, por lo qué tal cual sale compilada como .db lo subo al servidor.

**Comment by eclipxe13** [comment]
Creo que este problema está solucionado con el [release 1.2.0](https://github.com/phpcfdi/sat-catalogos-populate/releases/tag/v1.2.0). Que también incluye el nuevo formato de CCE Unidades de medida.

> ¿Se va a utilizar la misma tabla de fracciones arancelarias o se usará una nueva?

Decidí usar solo una sola tabla con ambos catálogos (8 y 10 dígitos).
Si en algún momento la estructura se vuelve incompatible pues será otro nuevo problema que resolver, tampoco puedo adivinar los futuros cambios y desastres del SAT. 

@valhallaws ojalá le puedas echar un ojo, por cierto, tenemos un canal de discord de la comunidad PhpCfdi en  https://discord.gg/aFGYXvX Si estás en este tema seguro te será de interés platicar allá.
